### ISSUE TITLE
index==0 creates wrong BDD

### ISSUE THREAD

**Issue by jpfr** [RenatoGeh/BDD.jl#2]
Thanks for providing the great library.

The docs say that index==-1 identifies a terminal node.
I was under the impression that any index >= 0 would be fine.
Yet I had to hunt down a nasty bug.

```julia
bdd1 = ⊤
for i=0:3
    bdd1 = bdd1 ∧ ¬variable(i)
end
println(bdd1)
```
generates a wrong BDD with a positive edge for the 1-index.
```
@ (index=0, id=6)
|  - (value=false, id=1)
|  + (index=1, id=5)
|  |  - (index=2, id=4)
|  |  |  - (index=3, id=3)
|  |  |  |  - (value=true, id=2)
|  |  |  |  + (value=false, id=1)
|  |  |  + (value=false, id=1)
|  |  + (value=false, id=1)
```

If I just increase the starting index to 1, the expected BDD is generated.
```julia
bdd1 = ⊤
for i=1:4
    bdd1 = bdd1 ∧ ¬variable(i)
end
println(bdd1)
```
```
@ (index=1, id=6)
|  - (index=2, id=5)
|  |  - (index=3, id=4)
|  |  |  - (index=4, id=3)
|  |  |  |  - (value=true, id=2)
|  |  |  |  + (value=false, id=1)
|  |  |  + (value=false, id=1)
|  |  + (value=false, id=1)
|  + (value=false, id=1)
```

That should be fixed or an assert included to catch "wrong" indizes.

**Comment by RenatoGeh** [comment]
> The docs say that index==-1 identifies a terminal node.

Indices must be strictly positive since we use `-index` to indicate a negation.

> I was under the impression that any index >= 0 would be fine.

You are right. This is not made clear in the docs. Thanks for the heads up.

> That should be fixed or an assert included to catch "wrong" indizes.

Done. See d96007f.

Bumped to 0.1.8. It should hit the Registry once https://github.com/JuliaRegistries/General/pull/79346 is merged.

**Comment by jpfr** [comment]
Nice! That was fast.
